version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    ports:
      - "5000:5000"
    networks:
      - songnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - songnet

networks:
  songnet:
    driver: bridge
